server {
    listen %%port%% default_server;
    allow 172.30.32.2;
    deny all;

    client_max_body_size 0;

    root /usr/share/pompey;
    index index.html;

    location = /status.json {
        alias /tmp/pompey/status.json;
        default_type application/json;
        add_header Cache-Control "no-store";
        access_log off;
    }

    location = /logo.png {
        access_log off;
    }

    location = /favicon.ico {
        access_log off;
    }

    location = /setup/proton {
        proxy_pass http://127.0.0.1:8097/setup/proton;
        proxy_set_header Content-Type $content_type;
        client_max_body_size 64k;
    }

    location / {
        add_header Cache-Control "no-store";
        try_files $uri $uri/ /index.html;
    }
}
